/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { OnFire as OnFire } from './components/on-fire/on-fire';

interface HTMLOnFireElement extends OnFire, HTMLElement {
}
declare var HTMLOnFireElement: {
  prototype: HTMLOnFireElement;
  new (): HTMLOnFireElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "on-fire": HTMLOnFireElement;
  }
  interface ElementTagNameMap {
      "on-fire": HTMLOnFireElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "on-fire": JSXElements.OnFireAttributes;
      }
  }
  namespace JSXElements {
      export interface OnFireAttributes extends HTMLAttributes {
        
          animated?: boolean | "true" | "false",
          message?: any
      }
  }
}

